version: '3.9'

services:
  ramapi: 
   container_name: ramapi_container
   image: oleksandrosipchuk/rickandmortyapi:latest
   ports:
   - 80:80
   networks: 
   - rickandmortyapi
   depends_on:
   - postgres_db

  postgres_db:
    container_name: ramdb_container
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 2002
    networks: 
    - rickandmortyapi
    volumes:
     - postgres_data:/var/lib/postgresql/data/
  
volumes: 
  postgres_data:

networks:
  rickandmortyapi:
    driver: bridge