version: '3.7'

services:

  reverseproxy:
   image: oleksandrosipchuk/reverseproxy
   container_name: reverseproxy
   ports:
    - 80:80
   restart: always
   networks: 
   - app

  rickandmortyapi: 
   image: oleksandrosipchuk/rickandmortyapi
   container_name: rickandmortyapi
   networks: 
   - app
   depends_on:
   - reverseproxy
   - postgres_db
   
  postgres_db:
    container_name: ramdb_container
    image: postgres
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=2002
    ports:
     - 5432:5432
    restart: always
    networks: 
    - app
    volumes:
     - postgres_data:/var/lib/postgresql/data/
  
volumes: 
  postgres_data:

networks:
  app:
    driver: bridge